//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial.Model
{
    public class Beneficiarios
    {
        public object IdBeneficiario { get; internal set; }
        public object Nombre { get; internal set; }
        public object Dui { get; internal set; }
    }
}